#server配置
server:
  port: 8088

#spring配置
spring:

  #rabbitMq配置
  rabbitmq:
    host: 120.48.107.224
    port: 5672
    username: admin
    password: admin
    virtual-host: 'java-test'
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: NONE
