#server配置
server:
  port: 8082

#spring配置
spring:

  #rabbitMq配置
  rabbitmq:
    primary:
      host: 120.48.107.224
      port: 5672
      username: admin
      password: admin
      virtual-host: 'java-test'
      acknowledge-mode: AUTO
    secondary:
      host: 120.48.107.224
      port: 5672
      username: admin
      password: admin
      virtual-host: '/'
      acknowledge-mode: MANUAL



